version: 3

services:
  front:
    build: .
    command: npm run preview
    ports:
      - "80:80"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    restart: always
    stdin_open: true