version: '3'

services:
  front:
    build: .
    command: npm run preview
    ports:
      - "8080:8080"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    restart: always
    stdin_open: true

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - front
    restart: always